# Generated by Django 4.0.3 on 2022-04-06 15:41

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(default=uuid.uuid1, max_length=100, unique=True)),
                ('guid', models.UUIDField(default=uuid.uuid4, null=True, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('R', models.IntegerField()),
                ('G', models.IntegerField()),
                ('B', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Common',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='block.common')),
                ('code', models.CharField(max_length=50)),
            ],
            bases=('block.common',),
        ),
        migrations.CreateModel(
            name='Geometry',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='block.common')),
            ],
            bases=('block.common',),
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='block.common')),
            ],
            bases=('block.common',),
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='block.common')),
            ],
            bases=('block.common',),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('block', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='block.block')),
            ],
        ),
        migrations.AddField(
            model_name='block',
            name='amount_units',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='b', to='block.unit'),
        ),
        migrations.AddField(
            model_name='block',
            name='severity_units',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='a', to='block.unit'),
        ),
        migrations.AddField(
            model_name='block',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='block.common')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='block.color')),
            ],
            bases=('block.common',),
        ),
        migrations.AddField(
            model_name='block',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='block.category'),
        ),
        migrations.AddField(
            model_name='block',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='block.condition'),
        ),
        migrations.AddField(
            model_name='block',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='block.material'),
        ),
        migrations.AddField(
            model_name='block',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='block.symbol'),
        ),
    ]
